name: karam
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  introduction_screen: ^3.1.14
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  intl: any
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.20.5
  flutter_riverpod: ^2.6.1
  go_router: ^14.6.1
  freezed_annotation: ^2.4.4
  build_runner: ^2.4.13
  size_setter: ^1.1.1
  bounce_tapper: ^1.0.9
  flutter_regex: ^0.0.3
  flutter_carousel_widget: ^3.1.0
  carousel_slider: ^5.0.0
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_lint: ^2.6.3
  freezed: ^2.5.7
  json_serializable: ^6.9.0
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/svg/tab_icons/active/
    - assets/svg/tab_icons/unActive/
    - assets/svg/
    - assets/lang/
    - assets/images/
    - assets/env/
  fonts:
    - family: SourceSansPro
      fonts:
        - asset: fonts/source-sans-pro/SourceSansPro-Black.otf
          weight: 900
        - asset: fonts/source-sans-pro/SourceSansPro-BlackIt.otf
          weight: 900
          style: italic
        - asset: fonts/source-sans-pro/SourceSansPro-Bold.otf
          weight: 700
        - asset: fonts/source-sans-pro/SourceSansPro-BoldIt.otf
          weight: 700
          style: italic
        - asset: fonts/source-sans-pro/SourceSansPro-ExtraLight.otf
          weight: 200
        - asset: fonts/source-sans-pro/SourceSansPro-ExtraLightIt.otf
          weight: 200
          style: italic
        - asset: fonts/source-sans-pro/SourceSansPro-It.otf
          style: italic
        - asset: fonts/source-sans-pro/SourceSansPro-Light.otf
          weight: 300
        - asset: fonts/source-sans-pro/SourceSansPro-LightIt.otf
          weight: 300
          style: italic
        - asset: fonts/source-sans-pro/SourceSansPro-Regular.otf
        - asset: fonts/source-sans-pro/SourceSansPro-Semibold.otf
          weight: 600
        - asset: fonts/source-sans-pro/SourceSansPro-SemiboldIt.otf
          weight: 600
          style: italic
